#!/bin/bash
# Download all files linked in the BOJ RSS feed
# https://www.boj.or.jp/en/rss/whatsnew.xml

DOWNLOAD_DIR="/Users/vrajpatel/All-projects/Market_Research/boj_downloads"
mkdir -p "$DOWNLOAD_DIR/pdf"
mkdir -p "$DOWNLOAD_DIR/xlsx"
mkdir -p "$DOWNLOAD_DIR/html_pages"

echo "=== Downloading PDF files ==="

# PDF files
curl -L -o "$DOWNLOAD_DIR/pdf/mpr260331a_quarterly_jgb_purchases.pdf" "http://www.boj.or.jp/en/mopo/mpmdeci/mpr_2026/mpr260331a.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/kess2602_payment_settlement_stats.pdf" "http://www.boj.or.jp/en/statistics/set/kess/release/2026/kess2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/yaku2602_avg_interest_rates.pdf" "http://www.boj.or.jp/en/statistics/dl/loan/yaku/yaku2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/ryudo_jgb_liquidity.pdf" "http://www.boj.or.jp/en/paym/bond/ryudo.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/opi260319_summary_opinions.pdf" "http://www.boj.or.jp/en/mopo/mpmsche_minu/opinion_2026/opi260319.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/g260123_minutes_jan.pdf" "http://www.boj.or.jp/en/mopo/mpmsche_minu/minu_2026/g260123.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/sppi2602_services_ppi.pdf" "http://www.boj.or.jp/en/statistics/pi/cspi_release/sppi2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/k260319a_monetary_policy_statement.pdf" "http://www.boj.or.jp/en/mopo/mpmdeci/mpr_2026/k260319a.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/sjgb2602_fails.pdf" "http://www.boj.or.jp/en/statistics/set/bffail/sjgb2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/cgpi2602_corporate_goods_price.pdf" "http://www.boj.or.jp/en/statistics/pi/cgpi_release/cgpi2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/kpolicy26_onsite_exam.pdf" "http://www.boj.or.jp/en/finsys/exam_monit/exampolicy/kpolicy26.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/ms2602_money_stock.pdf" "http://www.boj.or.jp/en/statistics/money/ms/ms2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/kasi2602_financial_institutions.pdf" "http://www.boj.or.jp/en/statistics/dl/depo/kashi/kasi2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/mbt2602_monetary_base_transactions.pdf" "http://www.boj.or.jp/en/statistics/boj/other/mbt/mbt2602.pdf"
curl -L -o "$DOWNLOAD_DIR/pdf/seifu2602_govt_transactions.pdf" "http://www.boj.or.jp/en/statistics/boj/other/tseifu/release/2026/seifu2602.pdf"

echo ""
echo "=== Downloading XLSX files ==="

# XLSX files
curl -L -o "$DOWNLOAD_DIR/xlsx/juqp2604_current_account_projections.xlsx" "http://www.boj.or.jp/en/statistics/boj/fm/juqp/juqp2604.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/mei260331_jgb_held.xlsx" "http://www.boj.or.jp/en/statistics/boj/other/mei/release/2026/mei260331.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/col2603_collateral.xlsx" "http://www.boj.or.jp/en/statistics/boj/other/col/col2603.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/juqf03_current_account_market_ops.xlsx" "http://www.boj.or.jp/en/statistics/boj/fm/juqf/juqf03.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/cabs_current_account_by_sector.xlsx" "http://www.boj.or.jp/en/statistics/boj/other/cabs/cabs.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/mei260319_jgb_held.xlsx" "http://www.boj.or.jp/en/statistics/boj/other/mei/release/2026/mei260319.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/mei260310_jgb_held.xlsx" "http://www.boj.or.jp/en/statistics/boj/other/mei/release/2026/mei260310.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/call_money_market.xlsx" "http://www.boj.or.jp/en/statistics/market/short/call/call.xlsx"
curl -L -o "$DOWNLOAD_DIR/xlsx/ope2602_market_operations.xlsx" "http://www.boj.or.jp/en/statistics/boj/fm/ope/m_release/2026/ope2602.xlsx"

echo ""
echo "=== Saving HTML page links ==="

# HTML pages (save as .html files via curl)
curl -L -o "$DOWNLOAD_DIR/html_pages/gap_output_gap_potential_growth.html" "http://www.boj.or.jp/en/research/research_data/gap/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/mb_monetary_base.html" "http://www.boj.or.jp/en/statistics/boj/other/mb/mb.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/tankan03b_comprehensive.html" "http://www.boj.or.jp/en/statistics/tk/tankan03b.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/tankan03a_summary.html" "http://www.boj.or.jp/en/statistics/tk/tankan03a.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/rev26e05_underlying_inflation.html" "http://www.boj.or.jp/en/research/wps_rev/rev_2026/rev26e05.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/dpse260330c_forecasting_recessions_ml.html" "http://www.boj.or.jp/en/research/imes/dps/dpse260330c.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/dpse260330b_shadow_rates.html" "http://www.boj.or.jp/en/research/imes/dps/dpse260330b.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/dpse260330a_computerization.html" "http://www.boj.or.jp/en/research/imes/dps/dpse260330a.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/rev26e04_natural_rate.html" "http://www.boj.or.jp/en/research/wps_rev/rev_2026/rev26e04.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/rel260326a_call_for_papers.html" "http://www.boj.or.jp/en/about/release_2026/rel260326a.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/cpi260326a_core_cpi_release.html" "http://www.boj.or.jp/en/research/research_data/cpi/cpi260326a.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/gap260326a_output_gap_update.html" "http://www.boj.or.jp/en/research/research_data/gap/gap260326a.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/cpi_index_core_cpi.html" "http://www.boj.or.jp/en/research/research_data/cpi/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/wp26e05_policy_reaction.html" "http://www.boj.or.jp/en/research/wps_rev/wps_2026/wp26e05.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/reri_real_exports_imports.html" "http://www.boj.or.jp/en/research/research_data/reri/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/ac260320_boj_accounts.html" "http://www.boj.or.jp/en/statistics/boj/other/acmai/release/2026/ac260320.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/ibs_bis_banking_stats.html" "http://www.boj.or.jp/en/statistics/bis/ibs/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/repo_sft_stats.html" "http://www.boj.or.jp/en/statistics/bis/repo/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/sj_flow_of_funds.html" "http://www.boj.or.jp/en/statistics/sj/sj.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/yoshi_derivatives_market.html" "http://www.boj.or.jp/en/statistics/bis/yoshi/index.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/ac260310_boj_accounts.html" "http://www.boj.or.jp/en/statistics/boj/other/acmai/release/2026/ac260310.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/rev26e02_supervisory_data.html" "http://www.boj.or.jp/en/research/wps_rev/rev_2026/rev26e02.htm"
curl -L -o "$DOWNLOAD_DIR/html_pages/cai_consumption_activity.html" "http://www.boj.or.jp/en/research/research_data/cai/index.htm"

echo ""
echo "=== Download complete ==="
echo ""
echo "Summary:"
echo "  PDFs:  $(ls -1 "$DOWNLOAD_DIR/pdf/" 2>/dev/null | wc -l) files in $DOWNLOAD_DIR/pdf/"
echo "  XLSX:  $(ls -1 "$DOWNLOAD_DIR/xlsx/" 2>/dev/null | wc -l) files in $DOWNLOAD_DIR/xlsx/"
echo "  HTML:  $(ls -1 "$DOWNLOAD_DIR/html_pages/" 2>/dev/null | wc -l) files in $DOWNLOAD_DIR/html_pages/"
echo ""
ls -lhS "$DOWNLOAD_DIR/pdf/"
echo ""
ls -lhS "$DOWNLOAD_DIR/xlsx/"
